/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package semver.test

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        assertTrue(true, "someLibraryMethod should return 'true'")
    }
}
